// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sustainai-dashboard/BrightOptimist.tsx": () => import("../components/mockups/sustainai-dashboard/BrightOptimist.tsx"),
  "./components/mockups/sustainai-dashboard/DeepFocus.tsx": () => import("../components/mockups/sustainai-dashboard/DeepFocus.tsx"),
  "./components/mockups/sustainai-dashboard/WarmEarth.tsx": () => import("../components/mockups/sustainai-dashboard/WarmEarth.tsx")
};
